import { MocDataItem } from "./typeDataItem";

// робимо плосикй обєкт для оптимізації отримання заих та спрощення структури отримання значень

export const MocDataLenovoY740: MocDataItem = {
  id: "1",
  title: "LENOVO LEGION Y740",
  price: 20000,
  sellPrice: null,
  description: "",
  images: [
    "https://ireland.apollo.olxcdn.com/v1/files/x2j2hh84yh9f2-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/iwk8kytl8rab1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/tegowjsvi7xt2-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/ku7mb0mwny49-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/40r8rv9uo4ha3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/7t1ry2cln1m51-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/xl0scocvq59e2-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/vs7m9c62bnt72-UA/image;s=1000x700",
  ],
  brand: "lenovo",
  display_size: "15.6",
  display_resolution: "1920x1080",
  display_type: "IPS",
  display_finish: "матовий",
  display_sensor: false,
  display_refreshRate: "144",
  cpu_name: "i7-9750H",
  cpu_brand: "Intel",
  cpu_gen: "9-го",
  cpu_power: "45",
  ram_type: "DDR4",
  ram_size: "16",
  ram_emptySlot: "0",
  mem_ssd_size: "512",
  mem_ssd_type: "M2",
  mem_ssd_emptySlots: "0",
  mem_hdd_size: "0",
  mem_hdd_emptySlots: "1",
  graphicsCard_discrete_brand: "Nvidia",
  graphicsCard_discrete_model: "GTX 1660 Ti",
  graphicsCard_discrete_memory: "3",
  graphicsCard_integrate_brand: "Intel",
  graphicsCard_integrate_model: "UHD Graphics 630",
  camera_mp: "1",
  camera_ir: false,
  ports_usbTypeA: "2",
  ports_usbTypeC: "2",
  ports_HDMI: "1",
  ports_DisplayPort: "1",
  ports_dvd: false,
  ports_audioJack: 1,
  ports_rj45: true,
  keyboard_numBlock: true,
  keyboard_light: "rgb",
  network_bluetooth: "5.0",
  network_wifi: "Killer Wireless-AC",
  network_sim: null,
  battery_twb: "3",
  dimensions_w: 361,
  dimensions_d: 265,
  dimensions_h: 23.85,
  dimensions_kg: 2.2,
  originalBox: false,
};

export const MocDataDellPrecision7740: MocDataItem = {
  id: "2",
  title: "Dell Precision 7740",
  price: 25000,
  sellPrice: null,
  description: "",
  images: [
    "https://ireland.apollo.olxcdn.com/v1/files/y3fuga9reszy1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/ltc3yxutwfvu1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/ltuibfuxv92u1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/cq3583fgoa132-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/2knnydromcl72-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/o7dr59cdxszq3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/8ko2naplvp81-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/6etri00y4eve1-UA/image;s=1000x700",
  ],
  brand: "dell",
  display_size: "17.3",
  display_resolution: "1920x1080",
  display_type: "IPS",
  display_finish: "матовий",
  display_sensor: false,
  display_refreshRate: "60",
  cpu_name: "i7-9750H",
  cpu_brand: "Intel",
  cpu_gen: "9-го",
  cpu_power: "45",
  ram_type: "DDR4",
  ram_size: "64",
  ram_emptySlot: "0",
  mem_ssd_size: "512",
  mem_ssd_type: "NVMe",
  mem_ssd_emptySlots: "0",
  mem_hdd_size: null,
  mem_hdd_emptySlots: "1",
  graphicsCard_discrete_brand: "Nvidia",
  graphicsCard_discrete_model: "Quadro RTX 4000",
  graphicsCard_discrete_memory: "8",
  graphicsCard_integrate_brand: "Intel",
  graphicsCard_integrate_model: "UHD Graphics 630",
  camera_mp: "0.92",
  camera_ir: false,
  ports_usbTypeA: "3",
  ports_usbTypeC: "2",
  ports_HDMI: "1",
  ports_DisplayPort: "1",
  ports_dvd: false,
  ports_audioJack: 1,
  ports_rj45: true,
  keyboard_numBlock: true,
  keyboard_light: "rgb",
  network_bluetooth: "5.0",
  network_wifi: "Wi-Fi 6",
  network_sim: null,
  battery_twb: "4",
  dimensions_w: 415,
  dimensions_d: 274,
  dimensions_h: 30.3,
  dimensions_kg: 3.08,
  originalBox: false,
};

export const MocDataMSIGF65Thin: MocDataItem = {
  id: "3",
  title: "MSI GF65 Thin",
  price: 20000,
  sellPrice: null,
  description: "",
  images: [
    "https://ireland.apollo.olxcdn.com/v1/files/vo8v26ewn1sx2-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/y0er9q510s6j1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/s9ufifcnbfqn3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/s8d6j00g0b6c3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/qrtyqfoayp9q3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/2f03y9gxdbwt1-UA/image;s=1000x700",
  ],
  brand: "msi",
  display_size: "15.6",
  display_resolution: "1920x1080",
  display_type: "IPS",
  display_finish: "матовий",
  display_sensor: false,
  display_refreshRate: "120",
  cpu_name: "i7-10850H",
  cpu_brand: "Intel",
  cpu_gen: "10-го",
  cpu_power: "45",
  ram_type: "DDR4",
  ram_size: "32",
  ram_emptySlot: "1",
  mem_ssd_size: "512",
  mem_ssd_type: "M2",
  mem_ssd_emptySlots: "1",
  mem_hdd_size: null,
  mem_hdd_emptySlots: "0",
  graphicsCard_discrete_brand: "Nvidia",
  graphicsCard_discrete_model: "GeForce RTX 3060 Max-Q",
  graphicsCard_discrete_memory: "6",
  graphicsCard_integrate_brand: "Intel",
  graphicsCard_integrate_model: "UHD Graphics 630",
  camera_mp: "0.92",
  camera_ir: false,
  ports_usbTypeA: "2",
  ports_usbTypeC: "2",
  ports_HDMI: "1",
  ports_DisplayPort: null,
  ports_dvd: false,
  ports_audioJack: 1,
  ports_rj45: true,
  keyboard_numBlock: true,
  keyboard_light: "only red",
  network_bluetooth: "5.0",
  network_wifi: "Wi-Fi 6",
  network_sim: null,
  battery_twb: "2",
  dimensions_w: 359,
  dimensions_d: 254,
  dimensions_h: 21.7,
  dimensions_kg: 1.86,
  originalBox: false,
};

export const MocDataMSIGS63VR7RF252US: MocDataItem = {
  id: "4",
  title: "MSI GS63VR 7RF-252US",
  price: 20000,
  sellPrice: null,
  description: "",
  images: [
    "https://ireland.apollo.olxcdn.com/v1/files/mxji0lr4hzaz-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/2pnfrivp1ppq1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/ffugnni1bdcu2-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/d3q654f19rfd3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/zznzmw8eiusb1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/lvdkkbwaeibw-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/a2j1t5snxmfb1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/3mufmg50lr7f1-UA/image;s=1000x700",
  ],
  brand: "msi",
  display_size: "15.6",
  display_resolution: "1920x1080",
  display_type: "IPS",
  display_finish: "матовий",
  display_sensor: false,
  display_refreshRate: "60",
  cpu_name: "i7-770HQ",
  cpu_brand: "Intel",
  cpu_gen: "7-го",
  cpu_power: "45",
  ram_type: "DDR4",
  ram_size: "16",
  ram_emptySlot: "1",
  mem_ssd_size: "256",
  mem_ssd_type: "M2",
  mem_ssd_emptySlots: "0",
  mem_hdd_size: null,
  mem_hdd_emptySlots: "1",
  graphicsCard_discrete_brand: "Nvidia",
  graphicsCard_discrete_model: "GeForce GTX 1060",
  graphicsCard_discrete_memory: "6",
  graphicsCard_integrate_brand: "Intel",
  graphicsCard_integrate_model: "UHD Graphics 630",
  camera_mp: "0.92",
  camera_ir: false,
  ports_usbTypeA: "3",
  ports_usbTypeC: "1",
  ports_HDMI: "1",
  ports_DisplayPort: "1",
  ports_dvd: false,
  ports_audioJack: 1,
  ports_rj45: true,
  keyboard_numBlock: true,
  keyboard_light: "rgb",
  network_bluetooth: "4.1",
  network_wifi: "Wi-Fi 5",
  network_sim: null,
  battery_twb: "1",
  dimensions_w: 380,
  dimensions_d: 249,
  dimensions_h: 17.7,
  dimensions_kg: 1.8,
  originalBox: false,
};

export const MocDataDellInspiron7610S: MocDataItem = {
  id: "5",
  title: "Dell Inspiron 7610",
  price: 22000,
  sellPrice: null,
  description: "",
  images: [
    "https://ireland.apollo.olxcdn.com/v1/files/vdzk85ylmgis1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/d970nubqieej3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/2der6lzlryyz2-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/2uiq71l6xmet-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/cne46srq6j6x1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/jmh34vmwbddo1-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/1p4dddybbu0k3-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/oq481x98ml2j3-UA/image;s=1000x700",
  ],
  brand: "dell",
  display_size: "16",
  display_resolution: "3072x1920",
  display_type: "WVA",
  display_finish: "матовий",
  display_sensor: false,
  display_refreshRate: "60",
  cpu_name: "i7-11800H",
  cpu_brand: "Intel",
  cpu_gen: "11-го",
  cpu_power: "45",
  ram_type: "DDR4",
  ram_size: "32",
  ram_emptySlot: "1",
  mem_ssd_size: "1 Tb",
  mem_ssd_type: "NVMe",
  mem_ssd_emptySlots: "0",
  mem_hdd_size: null,
  mem_hdd_emptySlots: "0",
  graphicsCard_discrete_brand: "Nvidia",
  graphicsCard_discrete_model: "GeForce RTX 3060",
  graphicsCard_discrete_memory: "6",
  graphicsCard_integrate_brand: "Intel",
  graphicsCard_integrate_model: "UHD Graphics 630",
  camera_mp: "0.92",
  camera_ir: false,
  ports_usbTypeA: "3",
  ports_usbTypeC: "1",
  ports_HDMI: "1",
  ports_DisplayPort: "1 mini",
  ports_dvd: false,
  ports_audioJack: 1,
  ports_rj45: true,
  keyboard_numBlock: true,
  keyboard_light: "rgb",
  network_bluetooth: "5.1",
  network_wifi: "Wi-Fi 6",
  network_sim: null,
  battery_twb: "4",
  dimensions_w: 380,
  dimensions_d: 249,
  dimensions_h: 17.7,
  dimensions_kg: 1.8,
  originalBox: false,
};

export const MocDataMSIBravo: MocDataItem = {
  id: "6",
  title: "MSI Bravo",
  price: 20000,
  sellPrice: null,
  description: "",
  images: [
    "https://ireland.apollo.olxcdn.com/v1/files/evharijljcmj-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/dat1ucm6m3693-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/a6zvarn5jj662-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/5a2ue9o8m6373-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/9ssynsmicwvr-UA/image;s=1000x700",
    "https://ireland.apollo.olxcdn.com/v1/files/sns5n8c34ii42-UA/image;s=1000x700",
  ],
  brand: "msi",
  display_size: "15.6",
  display_resolution: "1920x1080",
  display_type: "IPS",
  display_finish: "матовий",
  display_sensor: false,
  display_refreshRate: "144",
  cpu_name: "Ryzen 7 7535HS",
  cpu_brand: "AMD",
  cpu_gen: "7-го",
  cpu_power: "45",
  ram_type: "DDR5",
  ram_size: "16",
  ram_emptySlot: "1",
  mem_ssd_size: "512",
  mem_ssd_type: "M2",
  mem_ssd_emptySlots: "0",
  mem_hdd_size: null,
  mem_hdd_emptySlots: "0",
  graphicsCard_discrete_brand: "Nvidia",
  graphicsCard_discrete_model: "GeForce RTX 4050",
  graphicsCard_discrete_memory: "6",
  graphicsCard_integrate_brand: "AMD",
  graphicsCard_integrate_model: "Radeon 660M",
  camera_mp: "0.92",
  camera_ir: false,
  ports_usbTypeA: "3",
  ports_usbTypeC: "1",
  ports_HDMI: "1",
  ports_DisplayPort: "1",
  ports_dvd: false,
  ports_audioJack: 1,
  ports_rj45: true,
  keyboard_numBlock: true,
  keyboard_light: "rgb",
  network_bluetooth: "5.1",
  network_wifi: "Wi-Fi 6e",
  network_sim: null,
  battery_twb: "3",
  dimensions_w: 380,
  dimensions_d: 249,
  dimensions_h: 17.7,
  dimensions_kg: 1.8,
  originalBox: false,
};

export const arrayProducts = [
  MocDataLenovoY740,
  MocDataDellPrecision7740,
  MocDataMSIGF65Thin,
  MocDataMSIGS63VR7RF252US,
  MocDataDellInspiron7610S,
  MocDataMSIBravo,
];
